<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="admin__fieldset payment-method" 
    id="payment_form_<?= /* @noEscape */ $code ?>" style="display: none;">
    <?= $block->escapeHtml(
        __('In order to comply with PCI regulations, the administrator cannot capture this payment method.')
    ); ?>
</fieldset>

<script>
    require(["Magento_Sales/order/create/form"], function () {
        order.addExcludedPaymentMethod('{$code}');
    });
</script>
