<?php
/**
 * Copyright © MercadoPago. All rights reserved.
 *
 * @author      Bruno Elisei <brunoelisei@o2ti.com>
 * @license     See LICENSE for license details.
 */

/**
 * @var \Magento\Payment\Block\Adminhtml\Transparent\Form $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="admin__fieldset payment-method" 
    id="payment_form_<?= /* @noEscape */ $code ?>" 
    data-url-to-tokenize="<?= $block->escapeHtml($block->getUrlForTokenize()); ?>" style="display: none;">
    <?= $block->escapeHtml(
        __('Due to PCI compliance, it is not possible to capture this payment method by the administrator.')
    ); ?>
</fieldset>